# Generated by Django 3.0.7 on 2020-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
