# Generated by Django 3.0.7 on 2020-06-09 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200609_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Student')),
            ],
        ),
    ]
