# Generated by Django 3.0.7 on 2020-06-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200610_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='usn',
            field=models.CharField(max_length=20),
        ),
    ]
